# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

# Aliases are shorthand references for common settings.
aliases:
  # Docker Images
  - &use-github
    - image: cibuilds/github:0.10
      environment:
        GIT_AUTHOR_NAME: iubot
        GIT_AUTHOR_EMAIL: iubot@iu.edu
        GIT_COMMITTER_NAME: iubot
        GIT_COMMITTER_EMAIL: iubot@iu.edu

  # Cache Management
  - &restore-node-modules
    keys:
      - v1-node-modules-{{ checksum "package.json" }}
  - &save-node-modules
    paths:
      - node_modules
    key: v1-node-modules-{{ checksum "package.json" }}

  # Branch Filtering
  - &filter-only-master
    branches:
      only:
        - master

  - &filter-ignore-master
    branches:
      ignore:
        - master

  - &filter-only-develop
    branches:
      only:
        - develop

  # Tag Filtering
  - &filter-only-prereleases
    tags:
      only: /^v\d+\.\d+\.d+-(alpha|beta)$/

  - &filter-only-releases
    tags:
      only: /^v\d+\.\d+\.d+$/

defaults: &defaults
  working_directory: ~/rivet-collapsible
  docker:
    - image: circleci/node:7.10

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache: *restore-node-modules

      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Save cache settings
      - save_cache: *save-node-modules

      # Build!
      - run:
          name: Build components
          command: npm run build

  test:
    working_directory: ~/rivet-collapsible

    docker:
      - image: cypress/base:8

    environment:
      ## this enables colors in the output
      TERM: xterm

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache: *restore-node-modules

      # Install dependencies
      - run:
          name: Install dependencies
          command: npm install

      # Save cache settings
      - save_cache: *save-node-modules

      - run:
          command: npm headless
          background: true

      # Run tests
      - run:
          name: Run tests
          command: npm test

  publish_github:
    working_directory: ~/rivet-collapsible

    docker: *use-github

    steps:
      - attach_workspace:
        at: ./fake-folder

      - run:
        name: "Publish Release on Github"
        command: |
          VERSION=$(rivet-collapsible --version)
          ghr -t ${GH_TOKEN} -u ${GIT_AUTHOR_EMAIL} -r rivet-collapsible -c ${CIRCLE_SHA1} -delete ${VERSION} ./fake-folder/

  publish_package:
    <<: *defaults
    steps:
      - run:
          name: Get version
          command: echo $npm_package_version
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/rivet-collapsible/.npmrc
      - run:
          name: Publish package
          command: cd ~/rivet-collapsible/ && npm publish

workflows:
  version: 2
  build-test:
    jobs:
      - build:
          filters: *filter-ignore-master
      - test:
          requires:
            - build
  prerelease:
    jobs:
      - build:
          filters:
            <<: [*filter-only-develop, *filter-only-prereleases]
      - test:
          requires:
            - build
      - publish_github:
          requires:
            - test
          context: iubot
      - publish_package:
          requires:
            - publish_github
          context: iubot
  release:
    jobs:
      - build:
          filters:
            <<: [*filter-only-master, *filter-only-releases]
      - test:
          requires:
            - build
      - publish_github:
          requires:
            - test
          context: iubot
      - publish_package:
          requires:
            - publish_github
          context: iubot
