# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/rivet-collapsible
  docker:
  - image: circleci/node:7.10



jobs:
  build:
    <<: *defaults

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: npm install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    # run tests!
    - run: npm run build

  test:
    working_directory: ~/rivet-collapsible

    docker:
      - image: cypress/base:8
    environment:
      ## this enables colors in the output
      TERM: xterm

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install

      - run:
          command: node_modules/gulp/bin/gulp.js
          background: true

      # Run tests
      - run:
          name: Run tests
          command: $(npm bin)/cypress run

  npm:
    <<: *defaults
    steps:
    - run:
        name: Get version
        command: VERSION=$(node -pe "require('./package.json').version")
    - run:
        name: Authenticate with registry
        command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/rivet-collapsible/.npmrc
    - run:
        name: Publish package
        command: cd ~/rivet-collapsible/ && npm publish

workflows:
  version: 2
  build-test-npm:
    jobs:
    - build
    - test:
        requires:
        - build
    - npm:
        requires:
        - test
        filters:
          branches:
            only: master